<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-I3PT2JI" failures="2" tests="9" name="RetryMultipleTestCases" time="0.138" errors="0" timestamp="2021-03-18T20:06:49 ULAT">
  <testcase classname="myTests.MyTests" name="Test1" time="0.013">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="myTests.MyTests" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="myTests.MyTests" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="myTests.MyTests" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at myTests.MyTests.Test1(MyTests.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="myTests.MyTests" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="myTests.MyTests" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="myTests.MyTests" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="myTests.MyTests" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at myTests.MyTests.Test2(MyTests.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="myTests.MyTests" name="Test3" time="0.002"/>
</testsuite> <!-- RetryMultipleTestCases -->
